coslr: true
criterions:
  PerformanceLoss:
    def_file: ./loss/BalancedSoftmaxLoss.py
    loss_params: { freq_path: ./cls_freq/ImageNet_LT.json }
    optim_params: null
    weight: 1.0
endlr: 0.0
last: false
memory: { centroids: false, init_centroids: false }
model_dir: ./logs/ImageNet_LT/mislas
networks:
  classifier:
    def_file: ./models/DotProductClassifier.py
    optim_params: { lr: 0.5, momentum: 0.9, weight_decay: 0.0005 }
    params: { dataset: ImageNet_LT, feat_dim: 2048, num_classes: 1000, stage1_weights: false }
  feat_model:
    def_file: ./models/ResNet50Feature.py
    fix: true
    optim_params: { lr: 0.2, momentum: 0.9, weight_decay: 0.0005 }
    params: { dataset: ImageNet_LT, dropout: null, stage1_weights: false, use_fc: false, use_selfatt: false }
shuffle: true
training_opt:
  backbone: resnet50
  batch_size: 256
  dataset: ImageNet_LT
  display_step: 10
  feature_dim: 2048
  log_dir: ./logs/ImageNet_LT/mislas
  log_root: ./logs/ImageNet_LT
  num_classes: 1000
  num_epochs: 20
  num_workers: 12
  open_threshold: 0.1
  sampler: { def_file: ./data/MetaSampler.py, type: MetaSampler, meta_batch_size: 1024, init_pow: 0.1, lr: 0.001 }
  scheduler_params: { gamma: 0.1, step_size: 3 }
  stage: balms_resnet50
  sub_dir: clslearn
  fenduan: false
  weight_logits: false
  freq_path: ./cls_freq/ImageNet_LT.json
  norm_logits: true
  pow_for_logits: 1.0
  backward_weight_logits: none
