coslr: true
criterions:
  PerformanceLoss:
    def_file: ./loss/SoftmaxLoss.py
    loss_params: { }
    optim_params: null
    weight: 1.0
endlr: 0.0
gpu_id: 1
last: false
memory:
  centroids: false
  init_centroids: false
model_dir: ./resnext50
networks:
  classifier:
    def_file: ./models/DotProductClassifier.py
    optim_params:
      lr: 0.12
      momentum: 0.9
      weight_decay: 0.0005
    params:
      dataset: ImageNet_LT
      feat_dim: 2048
      freq_path: ./cls_freq/ImageNet_LT.json
      margin_cls: true
      margin_mode: pos_grad
      num_classes: 1000
      stage1_weights: false
      test: false
  feat_model:
    def_file: ./models/ResNext50Feature.py
    fix: true
    optim_params:
      lr: 0.12
      momentum: 0.9
      weight_decay: 0.0005
    params:
      dataset: ImageNet_LT
      dropout: null
      stage1_weights: false
      test: false
      use_fc: false
      use_selfatt: false
shuffle: true
training_opt:
  backbone: resnet50
  backward_weight_logits: none
  batch_size: 512
  dataset: ImageNet_LT
  display_step: 10
  feature_dim: 2048
  freq_path: ./cls_freq/ImageNet_LT.json
  log_dir: ./logs/ImageNet_LT/models/mislas_resnext
  log_root: ./logs/ImageNet_LT
  norm_logits: true
  num_classes: 1000
  num_epochs: 10
  num_workers: 6
  open_threshold: 0.1
  pow_for_logits: 1.0
  sampler:
    def_file: ./data/ClassAwareSampler.py
    num_samples_cls: 4
    type: ClassAwareSampler
  scheduler_params:
    gamma: 0.1
    step_size: 3
  stage: decpupled
  sub_dir: mislas
  weight_logits: false
