coslr: false
coslrwarmup: true
gpu_id: 1
criterions:
  PerformanceLoss:
    def_file: ./loss/SoftmaxLoss.py
    loss_params: {}
    optim_params: null
    weight: 1.0
endlr: 0.0
warmup_iterations: 200
base_lr: 0.05
warmup_lr: 0.1
last: false
memory: {centroids: false, init_centroids: false}
model_dir: null
networks:
  classifier:
    def_file: ./models/DotProductClassifier.py
    optim_params: {lr: 0.05, momentum: 0.9, weight_decay: 0.0005}
    params: {feat_dim: 64, num_classes: 100, margin_cls: true, margin_mode: pos_grad, freq_path: ./cls_freq/CIFAR-100-LT_IMBA200.json}
  feat_model:
    def_file: ./models/ResNet32Feature.py
    fix: false
    optim_params: {lr: 0.05, momentum: 0.9, weight_decay: 0.0005}
    params: {}
shuffle: false
training_opt:
  backward_weight_logits: none
  freq_path: ./cls_freq/CIFAR-100-LT_IMBA200.json
  weight_logits: false
  norm_logits: true
  pow_for_logits: 1
  backbone: resnet32
  batch_size: 64
  dataset: CIFAR100_LT
  display_step: 10
  feature_dim: 64
  log_dir: ./output/logs/CIFAR100_LT/models/resnet32_softmax_imba200_margin_cls
  # log_dir: ./logs/CIFAR100_LT/models/resnet32_softmax_imba200_cm
  # log_dir: ./output/logs/CIFAR100_LT/models/resnet32_softmax_imba200_norm_logits
  # log_dir: ./logs/CIFAR100_LT/models/resnet32_softmax_imba200_5
  num_classes: 100
  num_epochs: 200
  num_workers: 4
  open_threshold: 0.1
  sampler: null
  scheduler_params: {gamma: 0.1, step_size: 3}
  sub_dir: models
  cifar_imb_ratio: 200
